from .auth import router as auth_router
from .transactions import router as transactions_router
from .debts import router as debts_router
from .split_expenses import router as split_expenses_router
from .subscriptions import router as subscriptions_router
from .budgets import router as budgets_router
from .goals import router as goals_router
from .savings import router as savings_router
from .friends import router as friends_router
from .messages import router as messages_router
from .notifications import router as notifications_router
from .permissions import router as permissions_router
from .templates import router as templates_router
from .widgets import router as widgets_router
from .analytics import router as analytics_router
from .dashboard import router as dashboard_router
from .chat import router as chat_router
from .receipts import router as receipts_router
from .sms import router as sms_router